spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://dolphin-device-evident.ngrok-free.dev/eureka}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}