spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_db
        format_sql: false
        jdbc.time_zone: Asia/Seoul
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAPS}
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.yeoljeong.tripmate.*"
        spring.json.type.headers: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.headers: true

    listener:
      ack-mode: manual
      missing-topics-fatal: false

  properties:
    hibernate:
      format_sql: true
      default_schema: user

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOST_NAME}
    non-secure-port: 80
    prefer-ip-address: false