spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false