spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:tripmate_postgres}
    username: ${DB_USER:tripmate}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

# jwt
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000 # 30분
  refresh-token-expiration: 86400000 # 1일